void Cmd_amBan_F(gentity_t *ent);
void Cmd_amKick_F(gentity_t *ent);
void Cmd_amWarn_F(gentity_t *ent);
void Cmd_amTeleport_F(gentity_t *ent);
void Cmd_amAnnounce_F(gentity_t *ent);
void Cmd_amSilence_F(gentity_t *ent);
void Cmd_amUnSilence_F(gentity_t *ent);
void Cmd_amSleep_F(gentity_t *ent);
void Cmd_amUnsleep_F(gentity_t *ent);
void Cmd_amProtect_F(gentity_t *ent);
void Cmd_amListAdmins_F(gentity_t *ent);
void Cmd_amEmpower_F(gentity_t *ent);
void Cmd_amMerc_F(gentity_t *ent);
void Cmd_amEffect_F(gentity_t *ent);
void Cmd_amForceTeam_F(gentity_t *ent);
void Cmd_amMap_F(gentity_t *ent);
void G_RemoveWeather(void);
void Cmd_amWeather_F(gentity_t *ent);
void Cmd_amStatus_F(gentity_t *ent);
void uwRename(gentity_t *player, const char *newname);
void uw2Rename(gentity_t *player, const char *newname);
void Cmd_amRename_F(gentity_t *ent);
void Cmd_amSlap_F(gentity_t *ent);
void Cmd_info_F(gentity_t *ent);
void Cmd_aminfo_F(gentity_t *ent);
void Cmd_eminfo_F(gentity_t *ent);
void Cmd_GrantAdmin_F( gentity_t * ent );
void Cmd_SVGrantAdmin_F();
void Cmd_RemoveAdmin_F( gentity_t * ent );
void Cmd_SVRemoveAdmin_F();
void Cmd_GiveSkillPoints_F(gentity_t * ent);
void Cmd_FactionGenerateCredits_F(gentity_t * ent);
void Cmd_CreateFaction_F(gentity_t * ent);
void Cmd_SetFaction_F( gentity_t * ent );
void Cmd_SetFactionRank_F( gentity_t * ent );
void Cmd_FactionGenerate_F(gentity_t * ent);
void Cmd_GenerateCredits_F(gentity_t * ent);
void Cmd_CheatAccess_F( gentity_t *ent );
void Cmd_amWeatherPlus_F(gentity_t *ent);
void Cmd_ShakeScreen_F( gentity_t * ent );
void Cmd_Audio_F( gentity_t * ent );
void Cmd_amTelemark_F( gentity_t * ent );
void Cmd_amOrigin_F( gentity_t * ent );
void Cmd_AdminChat_F( gentity_t *ent );
void Cmd_Invisible_F( gentity_t * ent );
void Cmd_AllChat_F( gentity_t * ent );
void Cmd_amWarningList_F( gentity_t * ent );
