void Cmd_amBan_F(gentity_t *ent);
void Cmd_amKick_F(gentity_t *ent);
void Cmd_amWarn_F(gentity_t *ent);
void Cmd_amTeleport_F(gentity_t *ent);
void Cmd_amAnnounce_F(gentity_t *ent);
void Cmd_amMute_F(gentity_t *ent);
void Cmd_amUnMute_F(gentity_t *ent);
void Cmd_amSleep_F(gentity_t *ent);
void Cmd_amUnsleep_F(gentity_t *ent);
void Cmd_amProtect_F(gentity_t *ent);
void Cmd_amListAdmins_F(gentity_t *ent);
void Cmd_amEmpower_F(gentity_t *ent);
void Cmd_amMerc_F(gentity_t *ent);
void Cmd_amBitvalues_F(gentity_t *ent);
void Cmd_amEffect_F(gentity_t *ent);
void Cmd_amClearEffects_F(gentity_t *ent);
void Cmd_amForceTeam_F(gentity_t *ent);
void Cmd_amIP_F(gentity_t *ent);
void Cmd_amMap_F(gentity_t *ent);
void G_RemoveWeather(void);
void Cmd_amWeather_F(gentity_t *ent);
void Cmd_amStatus_F(gentity_t *ent);
void uwRename(gentity_t *player, const char *newname);
void uw2Rename(gentity_t *player, const char *newname);
void Cmd_amRename_F(gentity_t *ent);
void Cmd_amSlap_F(gentity_t *ent);
void Cmd_info_F(gentity_t *ent);
void Cmd_GrantAdmin_F( gentity_t * ent );
void Cmd_SVGrantAdmin_F();
void Cmd_RemoveAdmin_F( gentity_t * ent );
void Cmd_SVRemoveAdmin_F();
void Cmd_GenerateXP_F(gentity_t * ent);
void Cmd_FactionGenerateCredits_F(gentity_t * ent);
void Cmd_CreateFaction_F(gentity_t * ent);
void Cmd_SetFaction_F( gentity_t * ent );
void Cmd_KickFaction_F( gentity_t * ent );
void Cmd_SetFactionRank_F( gentity_t * ent );
void Cmd_FactionGenerate_F(gentity_t * ent);
void Cmd_GenerateCredits_F(gentity_t * ent);
void Cmd_CheatAccess_F( gentity_t *ent );
void Cmd_amWeatherPlus_F(gentity_t *ent);