void Cmd_amBan_f(gentity_t *ent);
void Cmd_amKick_f(gentity_t *ent);
void Cmd_amWarn_f(gentity_t *ent);
void Cmd_amTeleport_f(gentity_t *ent);
void Cmd_amSlay_f(gentity_t *ent);
void Cmd_amAnnounce_f(gentity_t *ent);
void Cmd_amMute_f(gentity_t *ent);
void Cmd_amUnMute_f(gentity_t *ent);
void Cmd_amSleep_f(gentity_t *ent);
void Cmd_amUnsleep_f(gentity_t *ent);
void Cmd_amProtect_f(gentity_t *ent);
void Cmd_amListAdmins_f(gentity_t *ent);
void Cmd_amEmpower_f(gentity_t *ent);
void Cmd_amMerc_f(gentity_t *ent);
void Cmd_amBitvalues_f(gentity_t *ent);
void Cmd_amEffect_f(gentity_t *ent);
void Cmd_amClearEffects_f(gentity_t *ent);
void Cmd_amForceTeam_f(gentity_t *ent);
void Cmd_amIP_f(gentity_t *ent);
void Cmd_amMap_f(gentity_t *ent);
void G_RemoveWeather( void );
void Cmd_amWeather_f(gentity_t *ent);
void Cmd_amStatus_f(gentity_t *ent);
void uwRename(gentity_t *player, const char *newname) ;
void uw2Rename(gentity_t *player, const char *newname) ;
void Cmd_amRename_f(gentity_t *ent);
void Cmd_amSlap_f(gentity_t *ent);